### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by mblais** [cjnaz/xbsjsonedit#1]
`xbsjsonedit v0.3 191206`

All commands result in a similar crash:
```
Enter option: d

Traceback (most recent call last):
  File "/home/matt/.local/bin/xbsjsonedit", line 524, in <module>
    main()
  File "/home/matt/.local/bin/xbsjsonedit", line 103, in main
    select = prompt("Enter option: ")
  File "/home/matt/.local/bin/xbsjsonedit", line 456, in prompt
    return (input(prompt_text))
  File "<string>", line 1, in <module>
NameError: name 'd' is not defined

**Comment by cjnaz** [comment]
When I googled this error it suggests that you are running on Python 2.7.

From the [README.md](https://github.com/cjnaz/xbsjsonedit/blob/master/README.md):
```
Known issues:

    This code only works with Python 3. Development and testing was done on Linux with Python 3.7.3.
```

What version of Python are you running?

**Comment by mblais** [comment]
Argh, and Doh!

Maybe change the first line of the script to
```
#!/usr/bin/env python3
```
That should help.
